import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";
import ReactQueryProvider from "@/lib/react-query-client";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // choose only weights you use
  variable: "--font-poppins", // optional for Tailwind integration
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className={`${poppins.className}`}>
        <Toaster
          toastOptions={{
            duration: 4000,
            position: 'top-center',
            style: {
              background: '#0a1526',
              color: '#2194FF',
              padding: '8px',
              fontSize: '14px',
              borderRadius: '10px',
              border: '1px solid #2194FF'
            },
            iconTheme: {
              primary: '#2194FF',
              secondary: '#0a1526'
            }
          }}
        />
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
                 <ReactQueryProvider>{children}</ReactQueryProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
